# Generated by Django 5.0.1 on 2024-01-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_alter_placeimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='images/category/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='url',
            field=models.ImageField(blank=True, upload_to='images/place/%Y/%m/%d/'),
        ),
    ]
