# Generated by Django 5.0.1 on 2024-01-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0003_alter_category_url_alter_placeimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
