# Generated by Django 5.0.1 on 2024-01-20 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0004_alter_placemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='git.placemodel'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='url',
            field=models.ImageField(upload_to='images/place/%Y/%m/%d/'),
        ),
    ]
