# Generated by Django 5.0.1 on 2024-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0005_alter_category_url_alter_placeimage_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='images/category/%Y/%m/%d/'),
        ),
    ]
