# Generated by Django 5.0.1 on 2024-02-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0006_alter_category_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placemodel',
            old_name='cat',
            new_name='category',
        ),
    ]
