# Generated by Django 5.0.1 on 2024-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0007_rename_cat_placemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemodel',
            name='quadkey',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
